-- Collections copy as authored templates, per tenant: the dunning policy's
-- steps reference these ids (templateId), so an operator edits the words in
-- one place. Norwegian statutory vocabulary (purregebyr, betalingsoppfordring,
-- inkassovarsel) appears in the nb bodies — it is the law's own language.
INSERT INTO message_template (id, href, tenant_id, name, channel, locales, created_at, last_update) VALUES
  ('dunning-reminder-genalpha', '/tmf-api/communicationManagement/v4/messageTemplate/dunning-reminder-genalpha',
   'genalpha', 'dunning-reminder', 'inApp',
   '{"en":{"subject":"Payment reminder","body":"Your account has an overdue balance of {{case.overdue}}. Please pay bill {{case.billNo}}. A statutory reminder fee may have been added."},"nb":{"subject":"Betalingspaminnelse","body":"Kontoen din har et forfalt belop pa {{case.overdue}}. Vennligst betal faktura {{case.billNo}}. Et purregebyr kan ha blitt lagt til."}}',
   CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('dunning-warning-genalpha', '/tmf-api/communicationManagement/v4/messageTemplate/dunning-warning-genalpha',
   'genalpha', 'dunning-warning', 'inApp',
   '{"en":{"subject":"Payment demand - action required","body":"Despite our reminder, {{case.overdue}} remains unpaid. Unless it is settled, outgoing services can be restricted or suspended at the earliest on {{case.enforceableAt}}. Emergency numbers always stay reachable."},"nb":{"subject":"Betalingsoppfordring - varsel om stenging","body":"Til tross for paminnelsen star {{case.overdue}} ubetalt. Uten betaling kan utgaende tjenester begrenses eller stenges tidligst {{case.enforceableAt}}. Nodnumre er alltid tilgjengelige."}}',
   CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('dunning-restricted-genalpha', '/tmf-api/communicationManagement/v4/messageTemplate/dunning-restricted-genalpha',
   'genalpha', 'dunning-restricted', 'inApp',
   '{"en":{"subject":"Outgoing services restricted","body":"As warned, outgoing calls are barred and data is reduced on your line. Emergency numbers still work. Pay {{case.overdue}} to lift the restriction."},"nb":{"subject":"Utgaende tjenester begrenset","body":"Som varslet er utgaende anrop sperret og data redusert. Nodnumre virker fortsatt. Betal {{case.overdue}} for a oppheve begrensningen."}}',
   CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('dunning-suspended-genalpha', '/tmf-api/communicationManagement/v4/messageTemplate/dunning-suspended-genalpha',
   'genalpha', 'dunning-suspended', 'inApp',
   '{"en":{"subject":"Your line is suspended","body":"Your line is suspended for nonpayment. No subscription charges accrue while it is suspended. Pay {{case.overdue}} to reconnect; a reconnection fee may apply."},"nb":{"subject":"Linjen din er stengt","body":"Linjen er stengt pa grunn av manglende betaling. Abonnementsavgifter loper ikke mens den er stengt. Betal {{case.overdue}} for a gjenapne; gjenapningsgebyr kan tilkomme."}}',
   CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('collection-cured-genalpha', '/tmf-api/communicationManagement/v4/messageTemplate/collection-cured-genalpha',
   'genalpha', 'collection-cured', 'inApp',
   '{"en":{"subject":"Thank you - services restored","body":"Your payment arrived and your services are restored. Welcome back."},"nb":{"subject":"Takk - tjenestene er gjenapnet","body":"Betalingen er mottatt og tjenestene dine er gjenapnet. Velkommen tilbake."}}',
   CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('promise-reminder-genalpha', '/tmf-api/communicationManagement/v4/messageTemplate/promise-reminder-genalpha',
   'genalpha', 'promise-reminder', 'inApp',
   '{"en":{"subject":"Your payment promise","body":"We registered your promise to pay {{promise.amount}} by {{promise.dueAt}}. Collection is paused until then."},"nb":{"subject":"Betalingsavtalen din","body":"Vi har registrert at du betaler {{promise.amount}} innen {{promise.dueAt}}. Innkreving er satt pa pause til da."}}',
   CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('dunning-reminder-nova', '/tmf-api/communicationManagement/v4/messageTemplate/dunning-reminder-nova',
   'nova', 'dunning-reminder', 'inApp',
   '{"en":{"subject":"Payment reminder","body":"Your account has an overdue balance of {{case.overdue}}. Please pay bill {{case.billNo}}. A statutory reminder fee may have been added."},"nb":{"subject":"Betalingspaminnelse","body":"Kontoen din har et forfalt belop pa {{case.overdue}}. Vennligst betal faktura {{case.billNo}}. Et purregebyr kan ha blitt lagt til."}}',
   CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('dunning-warning-nova', '/tmf-api/communicationManagement/v4/messageTemplate/dunning-warning-nova',
   'nova', 'dunning-warning', 'inApp',
   '{"en":{"subject":"Payment demand - action required","body":"Despite our reminder, {{case.overdue}} remains unpaid. Unless it is settled, outgoing services can be restricted or suspended at the earliest on {{case.enforceableAt}}. Emergency numbers always stay reachable."},"nb":{"subject":"Betalingsoppfordring - varsel om stenging","body":"Til tross for paminnelsen star {{case.overdue}} ubetalt. Uten betaling kan utgaende tjenester begrenses eller stenges tidligst {{case.enforceableAt}}. Nodnumre er alltid tilgjengelige."}}',
   CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('dunning-restricted-nova', '/tmf-api/communicationManagement/v4/messageTemplate/dunning-restricted-nova',
   'nova', 'dunning-restricted', 'inApp',
   '{"en":{"subject":"Outgoing services restricted","body":"As warned, outgoing calls are barred and data is reduced on your line. Emergency numbers still work. Pay {{case.overdue}} to lift the restriction."},"nb":{"subject":"Utgaende tjenester begrenset","body":"Som varslet er utgaende anrop sperret og data redusert. Nodnumre virker fortsatt. Betal {{case.overdue}} for a oppheve begrensningen."}}',
   CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('dunning-suspended-nova', '/tmf-api/communicationManagement/v4/messageTemplate/dunning-suspended-nova',
   'nova', 'dunning-suspended', 'inApp',
   '{"en":{"subject":"Your line is suspended","body":"Your line is suspended for nonpayment. No subscription charges accrue while it is suspended. Pay {{case.overdue}} to reconnect; a reconnection fee may apply."},"nb":{"subject":"Linjen din er stengt","body":"Linjen er stengt pa grunn av manglende betaling. Abonnementsavgifter loper ikke mens den er stengt. Betal {{case.overdue}} for a gjenapne; gjenapningsgebyr kan tilkomme."}}',
   CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('collection-cured-nova', '/tmf-api/communicationManagement/v4/messageTemplate/collection-cured-nova',
   'nova', 'collection-cured', 'inApp',
   '{"en":{"subject":"Thank you - services restored","body":"Your payment arrived and your services are restored. Welcome back."},"nb":{"subject":"Takk - tjenestene er gjenapnet","body":"Betalingen er mottatt og tjenestene dine er gjenapnet. Velkommen tilbake."}}',
   CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('promise-reminder-nova', '/tmf-api/communicationManagement/v4/messageTemplate/promise-reminder-nova',
   'nova', 'promise-reminder', 'inApp',
   '{"en":{"subject":"Your payment promise","body":"We registered your promise to pay {{promise.amount}} by {{promise.dueAt}}. Collection is paused until then."},"nb":{"subject":"Betalingsavtalen din","body":"Vi har registrert at du betaler {{promise.amount}} innen {{promise.dueAt}}. Innkreving er satt pa pause til da."}}',
   CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
