#!/usr/bin/env python3
"""Emit docker-compose.cloud.yml for a public host.

The base compose file hard-codes the Keycloak issuer as http://localhost:8085
(right for a laptop, wrong on a public box). On the box, browsers must reach
Keycloak at https://id.<domain>, and every token's `iss` must match what each
service's tenant registry expects. This override sets, for every service that
reads the tenant registry, the public issuer per tenant, and tells Keycloak
its public hostname behind the TLS proxy. Back-channel calls (service →
keycloak:8080) are untouched: KC_HOSTNAME_BACKCHANNEL_DYNAMIC stays on.
"""
import os, sys
import yaml

domain = os.environ.get("DEMO_DOMAIN", "taranga.no")
issuer_base = f"https://id.{domain}/realms"
base = yaml.safe_load(open("docker-compose.yml"))
tenants = yaml.safe_load(open("infra/tenants/tenants.yml"))
tenant_ids = [t["id"] for t in tenants["bss"]["tenants"]["registry"]] if "bss" in tenants else []

def wants_issuer(svc):
    env = svc.get("environment") or {}
    if isinstance(env, list):
        env = dict(e.split("=", 1) if "=" in e else (e, "") for e in env)
    keys = " ".join(env.keys())
    return "OIDC_ISSUER_URI" in keys or "SPRING_CONFIG_IMPORT" in keys

out = {"services": {}}
for name, svc in base["services"].items():
    if name == "keycloak":
        out["services"][name] = {"environment": {
            "KC_HOSTNAME": f"https://id.{domain}",
            "KC_HOSTNAME_BACKCHANNEL_DYNAMIC": "true",
            "KC_PROXY_HEADERS": "xforwarded",
            "KC_HTTP_ENABLED": "true",
        }}
        continue
    if not wants_issuer(svc):
        continue
    env = {"OIDC_ISSUER_URI": f"{issuer_base}/bss"}
    for tid in tenant_ids:
        if tid == "genalpha":
            continue
        env[f"OIDC_ISSUER_URI_{tid.upper()}"] = f"{issuer_base}/{tid}"
    out["services"][name] = {"environment": env}

sys.stdout.write("# GENERATED by ops/cloud/aws-demo/gen-override.py — public issuer + Keycloak hostname\n")
yaml.safe_dump(out, sys.stdout, sort_keys=False, default_flow_style=False)
