spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: product-catalog
          uri: ${CATALOG_URL:http://localhost:8081}
          predicates:
            - Path=/tmf-api/productCatalogManagement/**
        - id: product-ordering
          uri: ${ORDERING_URL:http://localhost:8082}
          predicates:
            - Path=/tmf-api/productOrderingManagement/**
        - id: product-inventory
          uri: ${INVENTORY_URL:http://localhost:8083}
          predicates:
            - Path=/tmf-api/productInventory/**
        - id: party-account
          uri: ${PARTY_URL:http://localhost:8084}
          predicates:
            - Path=/tmf-api/party/**,/tmf-api/accountManagement/**
        - id: admin-console
          uri: ${CONSOLE_URL:http://localhost:8090}
          predicates:
            - Path=/console/**
          filters:
            - StripPrefix=1

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,prometheus
  endpoint:
    health:
      show-details: never
  metrics:
    tags:
      application: ${spring.application.name}
