// GENERATED by ops/ontology/gen-sdk.mjs from the GenAlpha Operational Ontology — do not edit.
// Plain-JS twin of packages/genalpha-sdk/src/index.ts for apps without TypeScript.
// Registry: 7 concepts, 10 actions.

export class Refused extends Error {
  constructor(check, status) { super((check && check.refusal) || 'refused'); this.check = check; this.status = status; }
}

export class GenAlpha {
  /** @param {{ baseUrl: string, token: string | (() => string), channel?: string, fetch?: typeof fetch }} o */
  constructor(o) { this.o = o; }

  async call(method, path, body) {
    const f = this.o.fetch ?? fetch;
    const token = typeof this.o.token === 'function' ? this.o.token() : this.o.token;
    const r = await f(`${this.o.baseUrl}${path}`, { method, headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json', 'X-Channel': this.o.channel ?? 'web' }, body: body === undefined ? undefined : JSON.stringify(body) });
    const text = await r.text();
    let json = null; try { json = JSON.parse(text); } catch { json = { message: text }; }
    return { status: r.status, json };
  }

  /** The offerings a subscription could move up to: same family, on sale on this channel, dearer per month. */
  async availableUpgrades(subscriptionId) {
    const r = await this.call('GET', `/ontology/v1/subscriptions/${encodeURIComponent(subscriptionId)}/availableUpgrades`);
    if (r.status >= 300) throw new Error(`availableUpgrades: ${r.status}`);
    return r.json;
  }

  /** One call: a customer's subscriptions, lines, bills and decision receipts, walked with the caller's rights. */
  async customerContext(customerId) {
    const r = await this.call('GET', `/ontology/v1/context/customer/${encodeURIComponent(customerId)}`);
    if (r.status >= 300) throw new Error(`customerContext: ${r.status}`);
    return r.json;
  }

  /** What should be done next for a customer: governed actions dry-run through the registry, and things to explain. Grounded. */
  async recommendations(customerId) {
    const r = await this.call('GET', `/ontology/v1/context/customer/${encodeURIComponent(customerId)}/recommendations`);
    if (r.status >= 300) throw new Error(`recommendations: ${r.status}`);
    return r.json;
  }

  /** The ontology in words: kind is concept | action | page | journey. */
  async explain(kind, name) {
    const r = await this.call('GET', `/ontology/v1/explain/${kind}/${name}`);
    if (r.status >= 300) throw new Error(`explain ${kind} ${name}: ${r.status}`);
    return r.json;
  }

  /**
   * Approve a requested launch — good for the tenant's expiry window. Readiness still gates the launch itself, and a change to price, allowance, category, terms or channels voids the approval.
   * Who may: anyone holding catalog:approve.
   * Before it happens:
   *   - only a requested launch can be approved — a held one must be resumed first
   * @param {{ offeringId: string } & { note?: string }} inputs
   */
  async approveLaunch(inputs) {
    const r = await this.call('POST', '/ontology/v1/actions/approveLaunch/execute', inputs);
    if (r.status >= 300) throw new Refused(r.json?.check ?? r.json, r.status);
    return r.json;
  }

  /** Dry run of approveLaunch: may it happen, and if not, which condition fails? Nothing changes. */
  async checkApproveLaunch(inputs) {
    const r = await this.call('POST', '/ontology/v1/actions/approveLaunch/check', inputs);
    if (r.status >= 300) throw new Error(`check approveLaunch: ${r.status}`);
    return r.json;
  }

  /**
   * Cancel a product order that has not completed — reserved stock is released and card authorisations voided.
   * Who may: the owner themselves, or anyone holding ordering:write.
   * Before it happens:
   *   - a completed or already cancelled order cannot be cancelled
   * @param {{ orderId: string }} inputs
   */
  async cancelOrder(inputs) {
    const r = await this.call('POST', '/ontology/v1/actions/cancelOrder/execute', inputs);
    if (r.status >= 300) throw new Refused(r.json?.check ?? r.json, r.status);
    return r.json;
  }

  /** Dry run of cancelOrder: may it happen, and if not, which condition fails? Nothing changes. */
  async checkCancelOrder(inputs) {
    const r = await this.call('POST', '/ontology/v1/actions/cancelOrder/check', inputs);
    if (r.status >= 300) throw new Error(`check cancelOrder: ${r.status}`);
    return r.json;
  }

  /**
   * Open a dispute on a bill with a reason — collection never chases contested money while the dispute is open; finance resolves it with a credit or upholds the charge.
   * Who may: the owner themselves, or anyone holding billing:write.
   * Before it happens:
   *   - a dispute needs a reason — what looks wrong
   * @param {{ billId: string } & { reason: string }} inputs
   */
  async disputeBill(inputs) {
    const r = await this.call('POST', '/ontology/v1/actions/disputeBill/execute', inputs);
    if (r.status >= 300) throw new Refused(r.json?.check ?? r.json, r.status);
    return r.json;
  }

  /** Dry run of disputeBill: may it happen, and if not, which condition fails? Nothing changes. */
  async checkDisputeBill(inputs) {
    const r = await this.call('POST', '/ontology/v1/actions/disputeBill/check', inputs);
    if (r.status >= 300) throw new Error(`check disputeBill: ${r.status}`);
    return r.json;
  }

  /**
   * Pull the brake on a launch — a dated hold moves the on-sale date and lifts by itself; an open-ended hold takes a live offer off the shelf until someone resumes it.
   * Who may: anyone holding catalog:read.
   * Before it happens:
   *   - only a requested, approved or launched offering can be held
   * @param {{ offeringId: string } & { note?: string } & { until?: string }} inputs
   */
  async holdLaunch(inputs) {
    const r = await this.call('POST', '/ontology/v1/actions/holdLaunch/execute', inputs);
    if (r.status >= 300) throw new Refused(r.json?.check ?? r.json, r.status);
    return r.json;
  }

  /** Dry run of holdLaunch: may it happen, and if not, which condition fails? Nothing changes. */
  async checkHoldLaunch(inputs) {
    const r = await this.call('POST', '/ontology/v1/actions/holdLaunch/check', inputs);
    if (r.status >= 300) throw new Error(`check holdLaunch: ${r.status}`);
    return r.json;
  }

  /**
   * Issue a numbered credit note against a bill — what is due goes down, or a settled bill is refunded through the PSP. A care agent may credit small amounts on their own; above the threshold a finance approver decides; above the ceiling nobody may.
   * Who may: anyone holding billing:admin, or anyone holding agent.
   * Before it happens:
   *   - a credit note needs a reason
   *   - the credit must be more than zero and no more than what the bill still owes
   *   - no single credit above 50 — larger corrections are a finance decision, not a desk one
   * @param {{ billId: string } & { amount: number } & { reason: string }} inputs
   */
  async issueCredit(inputs) {
    const r = await this.call('POST', '/ontology/v1/actions/issueCredit/execute', inputs);
    if (r.status >= 300) throw new Refused(r.json?.check ?? r.json, r.status);
    return r.json;
  }

  /** Dry run of issueCredit: may it happen, and if not, which condition fails? Nothing changes. */
  async checkIssueCredit(inputs) {
    const r = await this.call('POST', '/ontology/v1/actions/issueCredit/check', inputs);
    if (r.status >= 300) throw new Error(`check issueCredit: ${r.status}`);
    return r.json;
  }

  /**
   * Block the old SIM at the network and issue a new one for the same number — the lost card dies first, then the new card is minted and the entitlement server rebound.
   * Who may: the owner themselves, or anyone holding service:write.
   * Before it happens:
   *   - only an active line can have its SIM replaced
   *   - the reason must be lost, stolen, damaged or upgrade
   * @param {{ serviceId: string } & { reason: string }} inputs
   */
  async replaceSim(inputs) {
    const r = await this.call('POST', '/ontology/v1/actions/replaceSim/execute', inputs);
    if (r.status >= 300) throw new Refused(r.json?.check ?? r.json, r.status);
    return r.json;
  }

  /** Dry run of replaceSim: may it happen, and if not, which condition fails? Nothing changes. */
  async checkReplaceSim(inputs) {
    const r = await this.call('POST', '/ontology/v1/actions/replaceSim/check', inputs);
    if (r.status >= 300) throw new Error(`check replaceSim: ${r.status}`);
    return r.json;
  }

  /**
   * Ask for a draft offering to be launched. Inside a pre-approved envelope it is approved at once and the trail names the envelope; otherwise it waits for an approver.
   * Who may: anyone holding catalog:write.
   * Before it happens:
   *   - only a draft can be requested for launch — a live offering is already launched
   *   - the launch must not already be requested, approved, held or launched
   * @param {{ offeringId: string } & { note?: string }} inputs
   */
  async requestLaunch(inputs) {
    const r = await this.call('POST', '/ontology/v1/actions/requestLaunch/execute', inputs);
    if (r.status >= 300) throw new Refused(r.json?.check ?? r.json, r.status);
    return r.json;
  }

  /** Dry run of requestLaunch: may it happen, and if not, which condition fails? Nothing changes. */
  async checkRequestLaunch(inputs) {
    const r = await this.call('POST', '/ontology/v1/actions/requestLaunch/check', inputs);
    if (r.status >= 300) throw new Error(`check requestLaunch: ${r.status}`);
    return r.json;
  }

  /**
   * Bring a paused line back — charging on, entitlements active, the same number.
   * Who may: the owner themselves, or anyone holding service:write.
   * Before it happens:
   *   - only a paused line can be resumed
   * @param {{ serviceId: string }} inputs
   */
  async resumeSubscription(inputs) {
    const r = await this.call('POST', '/ontology/v1/actions/resumeSubscription/execute', inputs);
    if (r.status >= 300) throw new Refused(r.json?.check ?? r.json, r.status);
    return r.json;
  }

  /** Dry run of resumeSubscription: may it happen, and if not, which condition fails? Nothing changes. */
  async checkResumeSubscription(inputs) {
    const r = await this.call('POST', '/ontology/v1/actions/resumeSubscription/check', inputs);
    if (r.status >= 300) throw new Error(`check resumeSubscription: ${r.status}`);
    return r.json;
  }

  /**
   * Pause a customer's line — charging stops, the phones lose their entitlements, the number is kept — open-ended or for a number of days, after which it resumes by itself.
   * Who may: the owner themselves, or anyone holding service:write.
   * Before it happens:
   *   - only an active line can be paused
   * @param {{ serviceId: string } & { reason?: string } & { days?: number }} inputs
   */
  async suspendSubscription(inputs) {
    const r = await this.call('POST', '/ontology/v1/actions/suspendSubscription/execute', inputs);
    if (r.status >= 300) throw new Refused(r.json?.check ?? r.json, r.status);
    return r.json;
  }

  /** Dry run of suspendSubscription: may it happen, and if not, which condition fails? Nothing changes. */
  async checkSuspendSubscription(inputs) {
    const r = await this.call('POST', '/ontology/v1/actions/suspendSubscription/check', inputs);
    if (r.status >= 300) throw new Error(`check suspendSubscription: ${r.status}`);
    return r.json;
  }

  /**
   * Move a customer's active subscription to a higher offering in the same family, in place — the line keeps its number, the bill prorates the month, the charging system and the phones learn the new plan.
   * Who may: the owner themselves, or anyone holding ordering:write.
   * Before it happens:
   *   - the subscription must be active — a suspended or ended line cannot be upgraded
   *   - the target offering must be on sale
   *   - the target offering must be sold on the channel the request comes from
   *   - the target must differ from the current offering
   *   - only a plan can be upgraded in place — a device or a pass is bought, not upgraded
   *   - an upgrade stays inside the same family — a mobile plan becomes another mobile plan
   *   - changing a plan into a bundle is not supported
   *   - the target must cost more per month than the current plan — otherwise it is a downgrade
   *   - the current plan must not be under an unexpired commitment
   *   - the offering must be deliverable where the customer lives, when it is place-gated
   * @param {{ subscriptionId: string } & { targetOfferingId: string }} inputs
   */
  async upgradeSubscription(inputs) {
    const r = await this.call('POST', '/ontology/v1/actions/upgradeSubscription/execute', inputs);
    if (r.status >= 300) throw new Refused(r.json?.check ?? r.json, r.status);
    return r.json;
  }

  /** Dry run of upgradeSubscription: may it happen, and if not, which condition fails? Nothing changes. */
  async checkUpgradeSubscription(inputs) {
    const r = await this.call('POST', '/ontology/v1/actions/upgradeSubscription/check', inputs);
    if (r.status >= 300) throw new Error(`check upgradeSubscription: ${r.status}`);
    return r.json;
  }

}
