// GENERATED by ops/ontology/gen-sdk.mjs from the GenAlpha Operational Ontology — do not edit.
// Regenerate after any registry change; the conformance suite diffs this file.
// Registry: 7 concepts, 11 actions, 41 capabilities.

export interface ClientOptions {
  /** the gateway base, e.g. https://demo.taranga.no */
  baseUrl: string;
  /** the bearer of the person or agent acting — every call runs with their own rights */
  token: string;
  /** the sales channel the request comes through (web, app, care, agent-mcp …) */
  channel?: string;
  fetch?: typeof fetch;
}

export interface Verdict { id: string; says: string; verdict: 'holds' | 'fails' | 'unknown'; detail?: string }
export interface Check {
  allowed: boolean;
  refusal?: string;
  preconditions: Verdict[];
  permission: { ok: boolean; by?: string; says: string; tried: string[] };
  policy: { decision: string; domain?: string; ruleName?: string; message?: string; says: string };
}
export interface Executed<T = unknown> extends Check {
  done: boolean;
  said: string;
  result?: T;
  decisionId?: string;
  effects?: { capability: string; when?: string }[];
  emits?: { event: string; component: string; meaning?: string }[];
}
export class Refused extends Error {
  constructor(public readonly check: Check, public readonly status: number) { super(check.refusal || 'refused'); }
}

/**
 * A customer's bill for a period — the month rated into lines, prorated where a plan changed mid-month.
 * SID: CustomerBill (Customer Bill ABE); TM Forum: TMF678 customerBill.
 * States (state): new, onHold, validated, sent, settled, partiallyPaid.
 */
export interface Bill {
  id: string;
  state?: "new" | "onHold" | "validated" | "sent" | "settled" | "partiallyPaid";
  /** amountDue.value */
  amountDue?: number;
  /** billDate */
  billDate?: string;
  [extra: string]: unknown;
}

/**
 * A person who holds subscriptions with the operator and pays for them — the party behind every line, order and bill.
 * SID: Customer (Customer ABE) / Individual (Party ABE); TM Forum: TMF632 individual, TMF629 customer.
 * States (status): initialized, validated, deceased.
 */
export interface Customer {
  id: string;
  status?: "initialized" | "validated" | "deceased";
  /** givenName */
  givenName?: string;
  /** familyName */
  familyName?: string;
  [extra: string]: unknown;
}

/**
 * What a line's phone may use — VoLTE, Wi-Fi calling, SMS over IP, companion eSIM — as the entitlement server derives it from the plan and tells the phone (GSMA TS.43).
 * SID: ServiceCharacteristic / Entitlement (extension); TM Forum: deviceEntitlement subscriber (house), TMF638 service.
 * States (status): bound, unbound.
 */
export interface Entitlement {
  id: string;
  status?: "bound" | "unbound";
  /** offeringId */
  offeringId?: string;
  /** the features the plan grants */
  features?: unknown[];
  [extra: string]: unknown;
}

/**
 * Something the operator sells — a plan, a pass, a device, a bundle — with its prices, its facts (specification) and the channels it is sold on.
 * SID: ProductOffering (Product Offering ABE); TM Forum: TMF620 productOffering.
 * States (lifecycleStatus): In study, In design, In test, Active, Launched, Retired, Obsolete.
 */
export interface ProductOffering {
  id: string;
  lifecycleStatus?: "In study" | "In design" | "In test" | "Active" | "Launched" | "Retired" | "Obsolete";
  /** name */
  name?: string;
  /** the family — Mobile plans, Broadband, Top-ups; a plan change stays inside one family */
  category?: string;
  /** isBundle */
  isBundle?: boolean;
  /** productOfferingPrice[priceType=recurring].price.value */
  monthlyPrice?: number;
  /** the OCS rate plan provisioned at activation */
  chargingSpecId?: string;
  [extra: string]: unknown;
}

/**
 * A request to create, change or end products for a customer — the transactional record of every commercial action.
 * SID: ProductOrder (Product Order ABE); TM Forum: TMF622 productOrder.
 * States (state): acknowledged, held, inProgress, partiallyCompleted, completed, failed, cancelled.
 */
export interface ProductOrder {
  id: string;
  state?: "acknowledged" | "held" | "inProgress" | "partiallyCompleted" | "completed" | "failed" | "cancelled";
  /** category */
  category?: string;
  /** orderDate */
  orderDate?: string;
  [extra: string]: unknown;
}

/**
 * The line itself as the network knows it — a mobile number, a fibre access — with its state and the resources under it.
 * SID: CustomerFacingService (Service ABE); TM Forum: TMF638 service, TMF641 serviceOrder.
 * States (state): feasibilityChecked, designed, reserved, inactive, active, suspended, terminated.
 */
export interface Service {
  id: string;
  state?: "feasibilityChecked" | "designed" | "reserved" | "inactive" | "active" | "suspended" | "terminated";
  /** name */
  name?: string;
  /** the number on the line */
  msisdn?: string;
  /** category */
  category?: string;
  [extra: string]: unknown;
}

/**
 * A customer's live instance of a product offering — "my 20 GB plan on this line". Canonical, because it spans the inventory's product (what was bought), the service (the line itself) and the charging and entitlement state behind it.
 * SID: ProductInstance (Product ABE); realized by CustomerFacingService (Service ABE); TM Forum: TMF637 product, TMF638 service, TMF622 productOrderItem.
 * States (status): created, pendingActive, active, suspended, pendingTerminate, terminated, aborted, cancelled.
 */
export interface Subscription {
  id: string;
  status?: "created" | "pendingActive" | "active" | "suspended" | "pendingTerminate" | "terminated" | "aborted" | "cancelled";
  /** the offering's name at the time of the last change */
  name?: string;
  /** startDate */
  startDate?: string;
  /** what it was before the last plan change — the bill prorates from offeringChangedAt */
  previousOffering?: string;
  /** offeringChangedAt */
  offeringChangedAt?: string;
  [extra: string]: unknown;
}

/**
 * Inputs of approveLaunch.
 */
export interface ApproveLaunchInputs {
  /** the requested offering (id of a ProductOffering) */
  offeringId: string;
  /** the approver's note */
  note?: string;
}

/**
 * Inputs of cancelOrder.
 */
export interface CancelOrderInputs {
  /** the order to cancel (id of a ProductOrder) */
  orderId: string;
}

/**
 * Inputs of disputeBill.
 */
export interface DisputeBillInputs {
  /** the bill in question (id of a Bill) */
  billId: string;
  /** what looks wrong */
  reason: string;
}

/**
 * Inputs of holdLaunch.
 */
export interface HoldLaunchInputs {
  /** the offering to hold (id of a ProductOffering) */
  offeringId: string;
  /** why */
  note?: string;
  /** when the hold lifts by itself (ISO date-time); empty = until resumed */
  until?: string;
}

/**
 * Inputs of issueCredit.
 */
export interface IssueCreditInputs {
  /** the bill to credit (id of a Bill) */
  billId: string;
  /** the credit, in the bill's currency */
  amount: number;
  /** the cause — a reversing document always has one */
  reason: string;
}

/**
 * Inputs of replaceSim.
 */
export interface ReplaceSimInputs {
  /** the line whose SIM is replaced (id of a Service) */
  serviceId: string;
  /** lost, stolen, damaged or upgrade */
  reason: string;
}

/**
 * Inputs of requestLaunch.
 */
export interface RequestLaunchInputs {
  /** the draft offering (id of a ProductOffering) */
  offeringId: string;
  /** a note for the approver */
  note?: string;
}

/**
 * Inputs of resumeSubscription.
 */
export interface ResumeSubscriptionInputs {
  /** the line to resume (id of a Service) */
  serviceId: string;
}

/**
 * Inputs of suspendSubscription.
 */
export interface SuspendSubscriptionInputs {
  /** the line to pause (id of a Service) */
  serviceId: string;
  /** why — vacation, lost phone, family rule (free text) */
  reason?: string;
  /** how many days (1–90); empty = until resumed */
  days?: number;
}

/**
 * Inputs of upgradeSubscription.
 */
export interface UpgradeSubscriptionInputs {
  /** the product instance to upgrade (id of a Subscription) */
  subscriptionId: string;
  /** the offering to move to (id of a ProductOffering) */
  targetOfferingId: string;
}

export class GenAlpha {
  constructor(private readonly o: ClientOptions) {}

  private async call(method: string, path: string, body?: unknown): Promise<{ status: number; json: any }> {
    const f = this.o.fetch ?? fetch;
    const r = await f(`${this.o.baseUrl}${path}`, { method, headers: { Authorization: `Bearer ${this.o.token}`, 'Content-Type': 'application/json', 'X-Channel': this.o.channel ?? 'web' }, body: body === undefined ? undefined : JSON.stringify(body) });
    const text = await r.text();
    let json: any = null; try { json = JSON.parse(text); } catch { json = { message: text }; }
    return { status: r.status, json };
  }

    /**
   * Read one Bill — Read one bill — its state, amount due and lines.
   */
  async bill(id: string): Promise<Bill> {
    const r = await this.call('GET', "/tmf-api/customerBillManagement/v4/customerBill/{id}".replace('{id}', encodeURIComponent(id)));
    if (r.status >= 300) throw new Error(`Bill ${id}: ${r.status}`);
    return r.json as Bill;
  }

    /**
   * Read one Customer — Read one individual — the person behind a customer.
   */
  async customer(id: string): Promise<Customer> {
    const r = await this.call('GET', "/tmf-api/partyManagement/v4/individual/{id}".replace('{id}', encodeURIComponent(id)));
    if (r.status >= 300) throw new Error(`Customer ${id}: ${r.status}`);
    return r.json as Customer;
  }

    /**
   * Read one ProductOffering — Read one product offering as the caller's sales channel sees it (X-Channel decides visibility).
   */
  async productOffering(id: string): Promise<ProductOffering> {
    const r = await this.call('GET', "/tmf-api/productCatalogManagement/v4/productOffering/{id}".replace('{id}', encodeURIComponent(id)));
    if (r.status >= 300) throw new Error(`ProductOffering ${id}: ${r.status}`);
    return r.json as ProductOffering;
  }

    /**
   * Read one ProductOrder — Read one product order and its state.
   */
  async productOrder(id: string): Promise<ProductOrder> {
    const r = await this.call('GET', "/tmf-api/productOrderingManagement/v4/productOrder/{id}".replace('{id}', encodeURIComponent(id)));
    if (r.status >= 300) throw new Error(`ProductOrder ${id}: ${r.status}`);
    return r.json as ProductOrder;
  }

    /**
   * Read one Service — Read one service — the line, with its state, number and restriction.
   */
  async service(id: string): Promise<Service> {
    const r = await this.call('GET', "/tmf-api/serviceInventory/v4/service/{id}".replace('{id}', encodeURIComponent(id)));
    if (r.status >= 300) throw new Error(`Service ${id}: ${r.status}`);
    return r.json as Service;
  }

    /**
   * Read one Subscription — Read one product instance — a customer's subscription as the inventory holds it.
   */
  async subscription(id: string): Promise<Subscription> {
    const r = await this.call('GET', "/tmf-api/productInventory/v4/product/{id}".replace('{id}', encodeURIComponent(id)));
    if (r.status >= 300) throw new Error(`Subscription ${id}: ${r.status}`);
    return r.json as Subscription;
  }

    /**
   * The offerings a subscription could move up to: same family, on sale on this channel, dearer per month.
   */
  async availableUpgrades(subscriptionId: string): Promise<{ id: string; name: string; monthly: number; family: string }[]> {
    const r = await this.call('GET', `/ontology/v1/subscriptions/${encodeURIComponent(subscriptionId)}/availableUpgrades`);
    if (r.status >= 300) throw new Error(`availableUpgrades: ${r.status}`);
    return r.json;
  }

    /**
   * One call: a customer's subscriptions (with what each could become), lines, bills and decision receipts — walked with the caller's rights; unanswered edges are listed.
   */
  async customerContext(customerId: string): Promise<{ customerId: string; customer?: { id: string; name: string; status: string }; subscriptions: unknown[]; services: unknown[]; bills: unknown[]; receipts: unknown[]; actionsAvailable: string[]; unanswered: string[] }> {
    const r = await this.call('GET', `/ontology/v1/context/customer/${encodeURIComponent(customerId)}`);
    if (r.status >= 300) throw new Error(`customerContext: ${r.status}`);
    return r.json;
  }

    /**
   * The ontology in words: a concept, an action, a console page or a whole journey.
   */
  async explain(kind: 'concept' | 'action' | 'page' | 'journey', name: string): Promise<{ kind: string; name: string; text: string; lines: string[]; steps?: unknown[] }> {
    const r = await this.call('GET', `/ontology/v1/explain/${kind}/${name}`);
    if (r.status >= 300) throw new Error(`explain ${kind} ${name}: ${r.status}`);
    return r.json;
  }

    /**
   * Approve a requested launch — good for the tenant's expiry window. Readiness still gates the launch itself, and a change to price, allowance, category, terms or channels voids the approval.
   * Who may: anyone holding catalog:approve.
   * Before it happens:
   * - only a requested launch can be approved — a held one must be resumed first
   * Governance: autonomy low, approval none, audit mandatory.
   * Version 1 (active).
   */
  async approveLaunch(inputs: ApproveLaunchInputs): Promise<Executed> {
    const r = await this.call('POST', '/ontology/v1/actions/approveLaunch/execute', inputs);
    if (r.status >= 300) throw new Refused(r.json?.check ?? r.json, r.status);
    return r.json as Executed;
  }

    /**
   * Dry run of approveLaunch: may it happen, and if not, which condition fails? Nothing changes.
   */
  async checkApproveLaunch(inputs: ApproveLaunchInputs): Promise<Check> {
    const r = await this.call('POST', '/ontology/v1/actions/approveLaunch/check', inputs);
    if (r.status >= 300) throw new Error(`check approveLaunch: ${r.status}`);
    return r.json as Check;
  }

    /**
   * Cancel a product order that has not completed — reserved stock is released and card authorisations voided.
   * Who may: the owner themselves, or anyone holding ordering:write.
   * Before it happens:
   * - a completed or already cancelled order cannot be cancelled
   * Governance: autonomy high, approval none, audit mandatory.
   * Version 1 (active).
   */
  async cancelOrder(inputs: CancelOrderInputs): Promise<Executed> {
    const r = await this.call('POST', '/ontology/v1/actions/cancelOrder/execute', inputs);
    if (r.status >= 300) throw new Refused(r.json?.check ?? r.json, r.status);
    return r.json as Executed;
  }

    /**
   * Dry run of cancelOrder: may it happen, and if not, which condition fails? Nothing changes.
   */
  async checkCancelOrder(inputs: CancelOrderInputs): Promise<Check> {
    const r = await this.call('POST', '/ontology/v1/actions/cancelOrder/check', inputs);
    if (r.status >= 300) throw new Error(`check cancelOrder: ${r.status}`);
    return r.json as Check;
  }

    /**
   * Open a dispute on a bill with a reason — collection never chases contested money while the dispute is open; finance resolves it with a credit or upholds the charge.
   * Who may: the owner themselves, or anyone holding billing:write.
   * Before it happens:
   * - a dispute needs a reason — what looks wrong
   * Governance: autonomy high, approval none, audit mandatory.
   * Version 1 (active).
   */
  async disputeBill(inputs: DisputeBillInputs): Promise<Executed> {
    const r = await this.call('POST', '/ontology/v1/actions/disputeBill/execute', inputs);
    if (r.status >= 300) throw new Refused(r.json?.check ?? r.json, r.status);
    return r.json as Executed;
  }

    /**
   * Dry run of disputeBill: may it happen, and if not, which condition fails? Nothing changes.
   */
  async checkDisputeBill(inputs: DisputeBillInputs): Promise<Check> {
    const r = await this.call('POST', '/ontology/v1/actions/disputeBill/check', inputs);
    if (r.status >= 300) throw new Error(`check disputeBill: ${r.status}`);
    return r.json as Check;
  }

    /**
   * Pull the brake on a launch — a dated hold moves the on-sale date and lifts by itself; an open-ended hold takes a live offer off the shelf until someone resumes it.
   * Who may: anyone holding catalog:read.
   * Before it happens:
   * - only a requested, approved or launched offering can be held
   * Governance: autonomy high, approval none, audit mandatory.
   * Version 1 (active).
   */
  async holdLaunch(inputs: HoldLaunchInputs): Promise<Executed> {
    const r = await this.call('POST', '/ontology/v1/actions/holdLaunch/execute', inputs);
    if (r.status >= 300) throw new Refused(r.json?.check ?? r.json, r.status);
    return r.json as Executed;
  }

    /**
   * Dry run of holdLaunch: may it happen, and if not, which condition fails? Nothing changes.
   */
  async checkHoldLaunch(inputs: HoldLaunchInputs): Promise<Check> {
    const r = await this.call('POST', '/ontology/v1/actions/holdLaunch/check', inputs);
    if (r.status >= 300) throw new Error(`check holdLaunch: ${r.status}`);
    return r.json as Check;
  }

    /**
   * Issue a numbered credit note against a bill — what is due goes down, or a settled bill is refunded through the PSP. A care agent may credit small amounts on their own; above the threshold a finance approver decides; above the ceiling nobody may.
   * Who may: anyone holding billing:admin, or anyone holding agent.
   * Before it happens:
   * - a credit note needs a reason
   * - the credit must be more than zero and no more than what the bill still owes
   * - no single credit above 50 — larger corrections are a finance decision, not a desk one
   * Governance: autonomy low, approval human, audit mandatory.
   * Version 1 (active).
   */
  async issueCredit(inputs: IssueCreditInputs): Promise<Executed> {
    const r = await this.call('POST', '/ontology/v1/actions/issueCredit/execute', inputs);
    if (r.status >= 300) throw new Refused(r.json?.check ?? r.json, r.status);
    return r.json as Executed;
  }

    /**
   * Dry run of issueCredit: may it happen, and if not, which condition fails? Nothing changes.
   */
  async checkIssueCredit(inputs: IssueCreditInputs): Promise<Check> {
    const r = await this.call('POST', '/ontology/v1/actions/issueCredit/check', inputs);
    if (r.status >= 300) throw new Error(`check issueCredit: ${r.status}`);
    return r.json as Check;
  }

    /**
   * Block the old SIM at the network and issue a new one for the same number — the lost card dies first, then the new card is minted and the entitlement server rebound.
   * Who may: the owner themselves, or anyone holding service:write.
   * Before it happens:
   * - only an active line can have its SIM replaced
   * - the reason must be lost, stolen, damaged or upgrade
   * Governance: autonomy low, approval none, audit mandatory.
   * Version 1 (active).
   */
  async replaceSim(inputs: ReplaceSimInputs): Promise<Executed> {
    const r = await this.call('POST', '/ontology/v1/actions/replaceSim/execute', inputs);
    if (r.status >= 300) throw new Refused(r.json?.check ?? r.json, r.status);
    return r.json as Executed;
  }

    /**
   * Dry run of replaceSim: may it happen, and if not, which condition fails? Nothing changes.
   */
  async checkReplaceSim(inputs: ReplaceSimInputs): Promise<Check> {
    const r = await this.call('POST', '/ontology/v1/actions/replaceSim/check', inputs);
    if (r.status >= 300) throw new Error(`check replaceSim: ${r.status}`);
    return r.json as Check;
  }

    /**
   * Ask for a draft offering to be launched. Inside a pre-approved envelope it is approved at once and the trail names the envelope; otherwise it waits for an approver.
   * Who may: anyone holding catalog:write.
   * Before it happens:
   * - only a draft can be requested for launch — a live offering is already launched
   * - the launch must not already be requested, approved, held or launched
   * Governance: autonomy medium, approval none, audit mandatory.
   * Version 1 (active).
   */
  async requestLaunch(inputs: RequestLaunchInputs): Promise<Executed> {
    const r = await this.call('POST', '/ontology/v1/actions/requestLaunch/execute', inputs);
    if (r.status >= 300) throw new Refused(r.json?.check ?? r.json, r.status);
    return r.json as Executed;
  }

    /**
   * Dry run of requestLaunch: may it happen, and if not, which condition fails? Nothing changes.
   */
  async checkRequestLaunch(inputs: RequestLaunchInputs): Promise<Check> {
    const r = await this.call('POST', '/ontology/v1/actions/requestLaunch/check', inputs);
    if (r.status >= 300) throw new Error(`check requestLaunch: ${r.status}`);
    return r.json as Check;
  }

    /**
   * Bring a paused line back — charging on, entitlements active, the same number.
   * Who may: the owner themselves, or anyone holding service:write.
   * Before it happens:
   * - only a paused line can be resumed
   * Governance: autonomy high, approval none, audit mandatory.
   * Version 1 (active).
   */
  async resumeSubscription(inputs: ResumeSubscriptionInputs): Promise<Executed> {
    const r = await this.call('POST', '/ontology/v1/actions/resumeSubscription/execute', inputs);
    if (r.status >= 300) throw new Refused(r.json?.check ?? r.json, r.status);
    return r.json as Executed;
  }

    /**
   * Dry run of resumeSubscription: may it happen, and if not, which condition fails? Nothing changes.
   */
  async checkResumeSubscription(inputs: ResumeSubscriptionInputs): Promise<Check> {
    const r = await this.call('POST', '/ontology/v1/actions/resumeSubscription/check', inputs);
    if (r.status >= 300) throw new Error(`check resumeSubscription: ${r.status}`);
    return r.json as Check;
  }

    /**
   * Pause a customer's line — charging stops, the phones lose their entitlements, the number is kept — open-ended or for a number of days, after which it resumes by itself.
   * Who may: the owner themselves, or anyone holding service:write.
   * Before it happens:
   * - only an active line can be paused
   * Governance: autonomy high, approval none, audit mandatory.
   * Version 1 (active).
   */
  async suspendSubscription(inputs: SuspendSubscriptionInputs): Promise<Executed> {
    const r = await this.call('POST', '/ontology/v1/actions/suspendSubscription/execute', inputs);
    if (r.status >= 300) throw new Refused(r.json?.check ?? r.json, r.status);
    return r.json as Executed;
  }

    /**
   * Dry run of suspendSubscription: may it happen, and if not, which condition fails? Nothing changes.
   */
  async checkSuspendSubscription(inputs: SuspendSubscriptionInputs): Promise<Check> {
    const r = await this.call('POST', '/ontology/v1/actions/suspendSubscription/check', inputs);
    if (r.status >= 300) throw new Error(`check suspendSubscription: ${r.status}`);
    return r.json as Check;
  }

    /**
   * Move a customer's active subscription to a higher offering in the same family, in place — the line keeps its number, the bill prorates the month, the charging system and the phones learn the new plan.
   * Who may: the owner themselves, or anyone holding ordering:write.
   * Before it happens:
   * - the subscription must be active — a suspended or ended line cannot be upgraded
   * - the target offering must be on sale
   * - the target offering must be sold on the channel the request comes from
   * - the target must differ from the current offering
   * - an upgrade stays inside the same family — a mobile plan becomes another mobile plan
   * - changing a plan into a bundle is not supported
   * - the target must cost more per month than the current plan — otherwise it is a downgrade
   * - the current plan must not be under an unexpired commitment
   * - the offering must be deliverable where the customer lives, when it is place-gated
   * Governance: autonomy medium, approval none, audit mandatory.
   * Version 1 (active).
   */
  async upgradeSubscription(inputs: UpgradeSubscriptionInputs): Promise<Executed> {
    const r = await this.call('POST', '/ontology/v1/actions/upgradeSubscription/execute', inputs);
    if (r.status >= 300) throw new Refused(r.json?.check ?? r.json, r.status);
    return r.json as Executed;
  }

    /**
   * Dry run of upgradeSubscription: may it happen, and if not, which condition fails? Nothing changes.
   */
  async checkUpgradeSubscription(inputs: UpgradeSubscriptionInputs): Promise<Check> {
    const r = await this.call('POST', '/ontology/v1/actions/upgradeSubscription/check', inputs);
    if (r.status >= 300) throw new Error(`check upgradeSubscription: ${r.status}`);
    return r.json as Check;
  }

}
