// GENERATED by ops/ontology/gen-sdk.mjs from the GenAlpha Operational Ontology — do not edit.
// Regenerate after any registry change; the conformance suite diffs this file.
// Registry: 7 concepts, 1 actions, 20 capabilities.

export interface ClientOptions {
  /** the gateway base, e.g. https://demo.taranga.no */
  baseUrl: string;
  /** the bearer of the person or agent acting — every call runs with their own rights */
  token: string;
  /** the sales channel the request comes through (web, app, care, agent-mcp …) */
  channel?: string;
  fetch?: typeof fetch;
}

export interface Verdict { id: string; says: string; verdict: 'holds' | 'fails' | 'unknown'; detail?: string }
export interface Check {
  allowed: boolean;
  refusal?: string;
  preconditions: Verdict[];
  permission: { ok: boolean; by?: string; says: string; tried: string[] };
  policy: { decision: string; domain?: string; ruleName?: string; message?: string; says: string };
}
export interface Executed<T = unknown> extends Check {
  done: boolean;
  said: string;
  result?: T;
  decisionId?: string;
  effects?: { capability: string; when?: string }[];
  emits?: { event: string; component: string; meaning?: string }[];
}
export class Refused extends Error {
  constructor(public readonly check: Check, public readonly status: number) { super(check.refusal || 'refused'); }
}

/**
 * A customer's bill for a period — the month rated into lines, prorated where a plan changed mid-month.
 * SID: CustomerBill (Customer Bill ABE); TM Forum: TMF678 customerBill.
 * States (state): new, onHold, validated, sent, settled, partiallyPaid.
 */
export interface Bill {
  id: string;
  state?: "new" | "onHold" | "validated" | "sent" | "settled" | "partiallyPaid";
  /** amountDue.value */
  amountDue?: number;
  /** billDate */
  billDate?: string;
  [extra: string]: unknown;
}

/**
 * A person who holds subscriptions with the operator and pays for them — the party behind every line, order and bill.
 * SID: Customer (Customer ABE) / Individual (Party ABE); TM Forum: TMF632 individual, TMF629 customer.
 * States (status): initialized, validated, deceased.
 */
export interface Customer {
  id: string;
  status?: "initialized" | "validated" | "deceased";
  /** givenName */
  givenName?: string;
  /** familyName */
  familyName?: string;
  [extra: string]: unknown;
}

/**
 * What a line's phone may use — VoLTE, Wi-Fi calling, SMS over IP, companion eSIM — as the entitlement server derives it from the plan and tells the phone (GSMA TS.43).
 * SID: ServiceCharacteristic / Entitlement (extension); TM Forum: deviceEntitlement subscriber (house), TMF638 service.
 * States (status): bound, unbound.
 */
export interface Entitlement {
  id: string;
  status?: "bound" | "unbound";
  /** offeringId */
  offeringId?: string;
  /** the features the plan grants */
  features?: unknown[];
  [extra: string]: unknown;
}

/**
 * Something the operator sells — a plan, a pass, a device, a bundle — with its prices, its facts (specification) and the channels it is sold on.
 * SID: ProductOffering (Product Offering ABE); TM Forum: TMF620 productOffering.
 * States (lifecycleStatus): In study, In design, In test, Active, Launched, Retired, Obsolete.
 */
export interface ProductOffering {
  id: string;
  lifecycleStatus?: "In study" | "In design" | "In test" | "Active" | "Launched" | "Retired" | "Obsolete";
  /** name */
  name?: string;
  /** the family — Mobile plans, Broadband, Top-ups; a plan change stays inside one family */
  category?: string;
  /** isBundle */
  isBundle?: boolean;
  /** productOfferingPrice[priceType=recurring].price.value */
  monthlyPrice?: number;
  /** the OCS rate plan provisioned at activation */
  chargingSpecId?: string;
  [extra: string]: unknown;
}

/**
 * A request to create, change or end products for a customer — the transactional record of every commercial action.
 * SID: ProductOrder (Product Order ABE); TM Forum: TMF622 productOrder.
 * States (state): acknowledged, held, inProgress, partiallyCompleted, completed, failed, cancelled.
 */
export interface ProductOrder {
  id: string;
  state?: "acknowledged" | "held" | "inProgress" | "partiallyCompleted" | "completed" | "failed" | "cancelled";
  /** category */
  category?: string;
  /** orderDate */
  orderDate?: string;
  [extra: string]: unknown;
}

/**
 * The line itself as the network knows it — a mobile number, a fibre access — with its state and the resources under it.
 * SID: CustomerFacingService (Service ABE); TM Forum: TMF638 service, TMF641 serviceOrder.
 * States (state): feasibilityChecked, designed, reserved, inactive, active, suspended, terminated.
 */
export interface Service {
  id: string;
  state?: "feasibilityChecked" | "designed" | "reserved" | "inactive" | "active" | "suspended" | "terminated";
  /** name */
  name?: string;
  /** the number on the line */
  msisdn?: string;
  /** category */
  category?: string;
  [extra: string]: unknown;
}

/**
 * A customer's live instance of a product offering — "my 20 GB plan on this line". Canonical, because it spans the inventory's product (what was bought), the service (the line itself) and the charging and entitlement state behind it.
 * SID: ProductInstance (Product ABE); realized by CustomerFacingService (Service ABE); TM Forum: TMF637 product, TMF638 service, TMF622 productOrderItem.
 * States (status): created, pendingActive, active, suspended, pendingTerminate, terminated, aborted, cancelled.
 */
export interface Subscription {
  id: string;
  status?: "created" | "pendingActive" | "active" | "suspended" | "pendingTerminate" | "terminated" | "aborted" | "cancelled";
  /** the offering's name at the time of the last change */
  name?: string;
  /** startDate */
  startDate?: string;
  /** what it was before the last plan change — the bill prorates from offeringChangedAt */
  previousOffering?: string;
  /** offeringChangedAt */
  offeringChangedAt?: string;
  [extra: string]: unknown;
}

/**
 * Inputs of upgradeSubscription.
 */
export interface UpgradeSubscriptionInputs {
  /** the product instance to upgrade (id of a Subscription) */
  subscriptionId: string;
  /** the offering to move to (id of a ProductOffering) */
  targetOfferingId: string;
}

export class GenAlpha {
  constructor(private readonly o: ClientOptions) {}

  private async call(method: string, path: string, body?: unknown): Promise<{ status: number; json: any }> {
    const f = this.o.fetch ?? fetch;
    const r = await f(`${this.o.baseUrl}${path}`, { method, headers: { Authorization: `Bearer ${this.o.token}`, 'Content-Type': 'application/json', 'X-Channel': this.o.channel ?? 'web' }, body: body === undefined ? undefined : JSON.stringify(body) });
    const text = await r.text();
    let json: any = null; try { json = JSON.parse(text); } catch { json = { message: text }; }
    return { status: r.status, json };
  }

    /**
   * Read one Customer — Read one individual — the person behind a customer.
   */
  async customer(id: string): Promise<Customer> {
    const r = await this.call('GET', "/tmf-api/partyManagement/v4/individual/{id}".replace('{id}', encodeURIComponent(id)));
    if (r.status >= 300) throw new Error(`Customer ${id}: ${r.status}`);
    return r.json as Customer;
  }

    /**
   * Read one ProductOffering — Read one product offering as the caller's sales channel sees it (X-Channel decides visibility).
   */
  async productOffering(id: string): Promise<ProductOffering> {
    const r = await this.call('GET', "/tmf-api/productCatalogManagement/v4/productOffering/{id}".replace('{id}', encodeURIComponent(id)));
    if (r.status >= 300) throw new Error(`ProductOffering ${id}: ${r.status}`);
    return r.json as ProductOffering;
  }

    /**
   * Read one ProductOrder — Read one product order and its state.
   */
  async productOrder(id: string): Promise<ProductOrder> {
    const r = await this.call('GET', "/tmf-api/productOrderingManagement/v4/productOrder/{id}".replace('{id}', encodeURIComponent(id)));
    if (r.status >= 300) throw new Error(`ProductOrder ${id}: ${r.status}`);
    return r.json as ProductOrder;
  }

    /**
   * Read one Subscription — Read one product instance — a customer's subscription as the inventory holds it.
   */
  async subscription(id: string): Promise<Subscription> {
    const r = await this.call('GET', "/tmf-api/productInventory/v4/product/{id}".replace('{id}', encodeURIComponent(id)));
    if (r.status >= 300) throw new Error(`Subscription ${id}: ${r.status}`);
    return r.json as Subscription;
  }

    /**
   * The offerings a subscription could move up to: same family, on sale on this channel, dearer per month.
   */
  async availableUpgrades(subscriptionId: string): Promise<{ id: string; name: string; monthly: number; family: string }[]> {
    const r = await this.call('GET', `/ontology/v1/subscriptions/${encodeURIComponent(subscriptionId)}/availableUpgrades`);
    if (r.status >= 300) throw new Error(`availableUpgrades: ${r.status}`);
    return r.json;
  }

    /**
   * The ontology in words: a concept, an action, a console page or a whole journey.
   */
  async explain(kind: 'concept' | 'action' | 'page' | 'journey', name: string): Promise<{ kind: string; name: string; text: string; lines: string[]; steps?: unknown[] }> {
    const r = await this.call('GET', `/ontology/v1/explain/${kind}/${name}`);
    if (r.status >= 300) throw new Error(`explain ${kind} ${name}: ${r.status}`);
    return r.json;
  }

    /**
   * Move a customer's active subscription to a higher offering in the same family, in place — the line keeps its number, the bill prorates the month, the charging system and the phones learn the new plan.
   * Who may: the owner themselves, or anyone holding ordering:write.
   * Before it happens:
   * - the subscription must be active — a suspended or ended line cannot be upgraded
   * - the target offering must be on sale
   * - the target offering must be sold on the channel the request comes from
   * - the target must differ from the current offering
   * - an upgrade stays inside the same family — a mobile plan becomes another mobile plan
   * - changing a plan into a bundle is not supported
   * - the target must cost more per month than the current plan — otherwise it is a downgrade
   * - the current plan must not be under an unexpired commitment
   * - the offering must be deliverable where the customer lives, when it is place-gated
   * Governance: autonomy medium, approval none, audit mandatory.
   * Version 1 (active).
   */
  async upgradeSubscription(inputs: UpgradeSubscriptionInputs): Promise<Executed> {
    const r = await this.call('POST', '/ontology/v1/actions/upgradeSubscription/execute', inputs);
    if (r.status >= 300) throw new Refused(r.json?.check ?? r.json, r.status);
    return r.json as Executed;
  }

    /**
   * Dry run of upgradeSubscription: may it happen, and if not, which condition fails? Nothing changes.
   */
  async checkUpgradeSubscription(inputs: UpgradeSubscriptionInputs): Promise<Check> {
    const r = await this.call('POST', '/ontology/v1/actions/upgradeSubscription/check', inputs);
    if (r.status >= 300) throw new Error(`check upgradeSubscription: ${r.status}`);
    return r.json as Check;
  }

}
