const { chromium } = require('playwright');
const SHOP = 'http://localhost:8080/shop/';
const run = Date.now();
(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage();
  const errs = [];
  page.on('console', m => { if (m.type() === 'error') errs.push(m.text()); });
  page.on('pageerror', e => errs.push('PAGEERROR: ' + e.message));
  await page.goto(SHOP);
  await page.locator('text=Sign in').first().click();
  await page.waitForSelector('a[href*="registration"], input[name="username"]', { timeout: 20000 });
  await page.click('a[href*="registration"]');
  await page.waitForSelector('input[name="email"]');
  await page.fill('input[name="firstName"]', 'P'); await page.fill('input[name="lastName"]', 'K');
  await page.fill('input[name="email"]', `dbg2-${run}@example.com`);
  await page.fill('input[name="password"]', 'Passw0rd!'); await page.fill('input[name="password-confirm"]', 'Passw0rd!');
  await page.click('input[type="submit"], button[type="submit"]');
  await page.waitForSelector('.hero', { timeout: 30000 });
  await page.locator('.card:has(h2:text-is("GenAlpha Mobile Unlimited 5G"))').first().click();
  await page.waitForSelector('.pricetable', { timeout: 15000 });
  await page.click('button.primary.big');
  await page.waitForURL('**/cart');
  await page.waitForTimeout(2000);
  const bodyText = (await page.locator('main').innerText()).slice(0, 500);
  console.log('--- CART main text ---\n' + bodyText);
  console.log('--- button.primary.big count:', await page.locator('button.primary.big').count());
  console.log('--- console errors:', JSON.stringify(errs.slice(0, 5)));
  await browser.close();
})().catch(e => { console.error('ERR:', e.message.split('\n')[0]); });
