/* The Keycloak master-realm admin, for the ten suites that mint their own user.
 *
 * Ten suites create a throwaway realm user so they can prove something about a
 * fresh customer. Each one did it by asking master for a token with a literal
 * `admin`/`admin`, then calling `.json()` on the answer and using it.
 *
 * That is two bugs wearing one coat:
 *
 *  1. The password is only `admin` on a laptop. `docker-compose.yml` spells it
 *     `${KEYCLOAK_ADMIN_PASSWORD:-admin}`, and the hosted box's installer
 *     generates a random one into its `.env` (ops/cloud/aws-demo/install.sh).
 *     So on the box every one of these admin calls was refused.
 *  2. A refused call still returns JSON. Keycloak answers 401 with an object,
 *     `.json()` hands it over without complaint, and the suite carries on with
 *     an error object where it expected a list. The first line to touch it
 *     throws — `roles.find is not a function` — which names a suite-side type
 *     error four lines below a credentials failure. Four suites reported
 *     exactly that in the first proof run on the box, and the message sent me
 *     looking at the wrong file.
 *
 * This is the shape I keep meeting: an error body read as a success body. A 404
 * whose four-key error object I once reported as "four offerings". So the rule
 * here is that nothing returns a parsed body without having proved the status,
 * and the message says which call was refused.
 */

// Matches docker-compose.yml's default, so a laptop needs no env at all.
const ADMIN_USER = process.env.KEYCLOAK_ADMIN_USERNAME || 'admin';
const ADMIN_PASS = process.env.KEYCLOAK_ADMIN_PASSWORD || 'admin';

/** A master-realm admin token, or an error that says the credentials were refused. */
async function adminToken(kcBase) {
  const url = `${kcBase}/realms/master/protocol/openid-connect/token`;
  const res = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: new URLSearchParams({
      grant_type: 'password',
      client_id: 'admin-cli',
      username: ADMIN_USER,
      password: ADMIN_PASS,
    }).toString(),
  });
  const body = await res.text();
  if (!res.ok) {
    throw new Error(
      `keycloak master admin refused the token for '${ADMIN_USER}' (HTTP ${res.status}). `
      + 'On the hosted box the password is generated by ops/cloud/aws-demo/install.sh — '
      + 'export KEYCLOAK_ADMIN_PASSWORD from the box .env before running the suites. '
      + `Keycloak said: ${body.slice(0, 200)}`);
  }
  const tok = JSON.parse(body).access_token;
  if (!tok) throw new Error(`keycloak returned 200 with no access_token: ${body.slice(0, 200)}`);
  return tok;
}

/**
 * An admin-API caller bound to one realm. Every verb proves the status before it
 * parses, so a refusal is reported where it happens and never flows on as data.
 */
function adminApi(kcBase, token, realm = 'bss') {
  const call = async (method, path, body) => {
    const res = await fetch(`${kcBase}/admin/realms/${realm}${path}`, {
      method,
      headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
      ...(body ? { body: JSON.stringify(body) } : {}),
    });
    const text = await res.text();
    // 409 is a realm object that already exists — the callers treat that as fine.
    if (!res.ok && res.status !== 409) {
      throw new Error(`keycloak admin ${method} ${path} failed (HTTP ${res.status}): ${text.slice(0, 200)}`);
    }
    return { status: res.status, text };
  };

  /** A JSON list from the admin API, proved to be a list before it is returned. */
  const list = async (path) => {
    const { status, text } = await call('GET', path);
    let parsed;
    try {
      parsed = JSON.parse(text);
    } catch {
      throw new Error(`keycloak admin GET ${path} returned non-JSON (HTTP ${status}): ${text.slice(0, 200)}`);
    }
    if (!Array.isArray(parsed)) {
      // The bug this module exists for: an object where a list was expected.
      throw new Error(
        `keycloak admin GET ${path} returned ${typeof parsed}, not a list (HTTP ${status}): `
        + `${text.slice(0, 200)}`);
    }
    return parsed;
  };

  return { call, list };
}

/**
 * Create an enabled realm user with a password, give it the named realm role,
 * and return its id. The whole dance the ten suites each wrote by hand.
 */
async function createRealmUser(kcBase, token, { username, firstName, lastName, password, role = 'customer' }) {
  const api = adminApi(kcBase, token);
  await api.call('POST', '/users', {
    username, email: username, enabled: true, emailVerified: true,
    firstName, lastName,
    credentials: [{ type: 'password', value: password, temporary: false }],
  });
  const users = await api.list(`/users?username=${encodeURIComponent(username)}`);
  if (users.length === 0) throw new Error(`keycloak created no user for ${username}`);
  const roles = await api.list('/roles');
  const wanted = roles.find((r) => r.name === role);
  if (!wanted) {
    throw new Error(`realm 'bss' has no role '${role}' — found ${roles.map((r) => r.name).join(', ')}`);
  }
  await api.call('POST', `/users/${users[0].id}/role-mappings/realm`, [wanted]);
  return users[0].id;
}

/**
 * The master-realm token request body, for the six suites that speak through a
 * Playwright APIRequestContext rather than `fetch` and so cannot use
 * `adminToken` above. They keep their own transport; this keeps the credentials
 * in one place, so the laptop default and the box's generated password are
 * resolved identically everywhere.
 */
const masterTokenForm = () => ({
  grant_type: 'password',
  client_id: 'admin-cli',
  username: ADMIN_USER,
  password: ADMIN_PASS,
});

/**
 * Prove an admin token actually arrived. A refused request answers 200-shaped
 * JSON with no `access_token`, and `undefined` in an Authorization header reads
 * as a 401 several calls later, which is how a credentials failure gets reported
 * as whatever the suite happened to touch next.
 */
function assertAdminToken(tok) {
  if (!tok) {
    throw new Error(
      `keycloak master admin refused the token for '${ADMIN_USER}'. On the hosted box the `
      + 'password is generated by ops/cloud/aws-demo/install.sh — export KEYCLOAK_ADMIN_PASSWORD '
      + 'from the box .env before running the suites.');
  }
  return tok;
}

module.exports = {
  adminToken, adminApi, createRealmUser, masterTokenForm, assertAdminToken,
  ADMIN_USER, ADMIN_PASS,
};
