#!/usr/bin/env node
// The GenAlpha Ontology SDK, generated from the registry — never hand-written.
//
//   node ops/ontology/gen-sdk.mjs [out=packages/genalpha-sdk/src/index.ts] [api=http://localhost:8080] [realm=bss]
//
// Reads the merged core registry (concepts, actions, capabilities) from the running
// service with a staff token and writes a typed TypeScript client: one interface per
// concept, one function per action (check + execute), the available-upgrades read,
// and explain(). The conformance suite (#125) regenerates this file and fails when
// the committed copy differs: a changed definition is a changed contract.
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';

const OUT = process.argv[2] || 'packages/genalpha-sdk/src/index.ts';
const API = process.argv[3] || process.env.API || 'http://localhost:8080';
const REALM = process.argv[4] || process.env.REALM || 'bss';
const [USER, PASS] = [process.env.SEED_USER || 'demo', process.env.SEED_PASS || 'demo'];

async function token() {
  const res = await fetch(`http://localhost:8085/realms/${REALM}/protocol/openid-connect/token`, {
    method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: new URLSearchParams({ grant_type: 'password', client_id: 'bss-demo', username: USER, password: PASS }) });
  return (await res.json()).access_token;
}
const tok = await token();
const get = async (p) => { const r = await fetch(`${API}/ontology/v1${p}`, { headers: { Authorization: 'Bearer ' + tok } }); if (!r.ok) throw new Error(`${p}: ${r.status}`); return r.json(); };
const [concepts, actions, capabilities] = await Promise.all([get('/concepts'), get('/actions'), get('/capabilities')]);

const tsType = (t) => ({ number: 'number', money: 'number', boolean: 'boolean', date: 'string', list: 'unknown[]' }[t] || 'string');
const pascal = (s) => s.charAt(0).toUpperCase() + s.slice(1);
const doc = (lines, indent = '') => `${indent}/**\n${lines.filter(Boolean).map((l) => `${indent} * ${l}`).join('\n')}\n${indent} */`;
const who = (a) => (a.permissions?.anyOf || []).map((c) => c.self ? `the ${c.self} themselves` : `anyone holding ${c.role}`).join(', or ');

let out = `// GENERATED by ops/ontology/gen-sdk.mjs from the GenAlpha Operational Ontology — do not edit.
// Regenerate after any registry change; the conformance suite diffs this file.
// Registry: ${concepts.length} concepts, ${actions.length} actions, ${capabilities.length} capabilities.

export interface ClientOptions {
  /** the gateway base, e.g. https://demo.taranga.no */
  baseUrl: string;
  /** the bearer of the person or agent acting — every call runs with their own rights */
  token: string;
  /** the sales channel the request comes through (web, app, care, agent-mcp …) */
  channel?: string;
  fetch?: typeof fetch;
}

export interface Verdict { id: string; says: string; verdict: 'holds' | 'fails' | 'unknown'; detail?: string }
export interface Check {
  allowed: boolean;
  refusal?: string;
  preconditions: Verdict[];
  permission: { ok: boolean; by?: string; says: string; tried: string[] };
  policy: { decision: string; domain?: string; ruleName?: string; message?: string; says: string };
}
export interface Executed<T = unknown> extends Check {
  done: boolean;
  said: string;
  result?: T;
  decisionId?: string;
  effects?: { capability: string; when?: string }[];
  emits?: { event: string; component: string; meaning?: string }[];
}
export class Refused extends Error {
  constructor(public readonly check: Check, public readonly status: number) { super(check.refusal || 'refused'); }
}

`;

for (const c of concepts) {
  const lines = [c.meaning, `SID: ${c.lineage?.sid}; TM Forum: ${(c.lineage?.tmf || []).join(', ')}.`,
    `States (${c.states?.field}): ${(c.states?.values || []).join(', ')}.`];
  out += `${doc(lines)}\nexport interface ${c.concept} {\n  id: string;\n  ${c.states?.field}?: ${(c.states?.values || []).map((v) => JSON.stringify(v)).join(' | ')};\n`;
  for (const p of c.properties || []) out += `  /** ${p.meaning || p.path} */\n  ${p.name}?: ${tsType(p.type)};\n`;
  out += `  [extra: string]: unknown;\n}\n\n`;
}

for (const a of actions) {
  const name = pascal(a.action);
  out += `${doc([`Inputs of ${a.action}.`])}\nexport interface ${name}Inputs {\n`;
  for (const i of a.inputs || []) out += `  /** ${i.meaning || i.name}${i.concept ? ` (id of a ${i.concept})` : ''} */\n  ${i.name}${i.required ? '' : '?'}: ${tsType(i.type)};\n`;
  out += `}\n\n`;
}

out += `export class GenAlpha {\n  constructor(private readonly o: ClientOptions) {}\n\n  private async call(method: string, path: string, body?: unknown): Promise<{ status: number; json: any }> {\n    const f = this.o.fetch ?? fetch;\n    const r = await f(\`\${this.o.baseUrl}\${path}\`, { method, headers: { Authorization: \`Bearer \${this.o.token}\`, 'Content-Type': 'application/json', 'X-Channel': this.o.channel ?? 'web' }, body: body === undefined ? undefined : JSON.stringify(body) });\n    const text = await r.text();\n    let json: any = null; try { json = JSON.parse(text); } catch { json = { message: text }; }\n    return { status: r.status, json };\n  }\n\n`;

for (const c of concepts) {
  const cap = capabilities.find((x) => x.id === c.backedBy?.capability);
  if (cap?.route?.path?.includes('{id}')) {
    out += `  ${doc([`Read one ${c.concept} — ${cap.meaning}`], '  ')}\n  async ${c.concept.charAt(0).toLowerCase() + c.concept.slice(1)}(id: string): Promise<${c.concept}> {\n    const r = await this.call('GET', ${JSON.stringify(cap.route.path)}.replace('{id}', encodeURIComponent(id)));\n    if (r.status >= 300) throw new Error(\`${c.concept} \${id}: \${r.status}\`);\n    return r.json as ${c.concept};\n  }\n\n`;
  }
}

out += `  ${doc(['The offerings a subscription could move up to: same family, on sale on this channel, dearer per month.'], '  ')}\n  async availableUpgrades(subscriptionId: string): Promise<{ id: string; name: string; monthly: number; family: string }[]> {\n    const r = await this.call('GET', \`/ontology/v1/subscriptions/\${encodeURIComponent(subscriptionId)}/availableUpgrades\`);\n    if (r.status >= 300) throw new Error(\`availableUpgrades: \${r.status}\`);\n    return r.json;\n  }\n\n`;
out += `  ${doc(['The ontology in words: a concept, an action, a console page or a whole journey.'], '  ')}\n  async explain(kind: 'concept' | 'action' | 'page' | 'journey', name: string): Promise<{ kind: string; name: string; text: string; lines: string[]; steps?: unknown[] }> {\n    const r = await this.call('GET', \`/ontology/v1/explain/\${kind}/\${name}\`);\n    if (r.status >= 300) throw new Error(\`explain \${kind} \${name}: \${r.status}\`);\n    return r.json;\n  }\n\n`;

for (const a of actions) {
  const name = pascal(a.action);
  const pcs = (a.preconditions || []).map((p) => `- ${p.says}`);
  out += `  ${doc([a.meaning, `Who may: ${who(a)}.`, 'Before it happens:', ...pcs, `Governance: autonomy ${a.governance?.autonomy}, approval ${a.governance?.approval}, audit ${a.governance?.audit}.`, `Version ${a.version} (${a.status}).`], '  ')}\n`;
  out += `  async ${a.action}(inputs: ${name}Inputs): Promise<Executed> {\n    const r = await this.call('POST', '/ontology/v1/actions/${a.action}/execute', inputs);\n    if (r.status >= 300) throw new Refused(r.json?.check ?? r.json, r.status);\n    return r.json as Executed;\n  }\n\n`;
  out += `  ${doc([`Dry run of ${a.action}: may it happen, and if not, which condition fails? Nothing changes.`], '  ')}\n  async check${name}(inputs: ${name}Inputs): Promise<Check> {\n    const r = await this.call('POST', '/ontology/v1/actions/${a.action}/check', inputs);\n    if (r.status >= 300) throw new Error(\`check ${a.action}: \${r.status}\`);\n    return r.json as Check;\n  }\n\n`;
}
out += `}\n`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, out);
console.log(`wrote ${OUT}: ${concepts.length} concepts, ${actions.length} actions`);
