#!/usr/bin/env bash
# A FLEET SMALL ENOUGH FOR A RUNNER.
#
# The laptop fleet is 95 services and ops/fleet.sh says the full shape "wants
# 24-32GB free for comfort". A GitHub-hosted runner has 16GB (public repos) or
# 7GB (private). So the browser tier in CI cannot be the whole fleet; it has to
# be a named slice, with the JVMs told to be modest.
#
#   ops/ci-fleet.sh smoke     the storefront slice — what a PR can afford
#   ops/ci-fleet.sh full      everything (needs a big runner or a laptop)
#
# Exits non-zero when the fleet does not come ready, and prints the logs of
# whatever is unhealthy — a CI failure you cannot diagnose is a CI failure you
# will disable.
set -uo pipefail
cd "$(dirname "$0")/.."

TIER="${1:-smoke}"
HEAP="${CI_FLEET_HEAP:-192m}"
READY_TIMEOUT="${CI_FLEET_TIMEOUT:-600}"

# The storefront slice: the front door, the identity provider, the stores the
# shop actually reads, and the storefront itself. Derived from the paths
# apps/storefront calls, mapped through the gateway's routes.
#
# MEASURED, not guessed (23 Sep 2026, laptop, fleet stopped): asking for these
# 18 starts 33 containers — compose honours depends_on and drags in billing,
# som, assurance, usage, the consoles and more — using ~10.0GiB with every JVM
# capped (11.4GiB when only the named 18 were capped, which is why the cap
# below covers all of them). That fits a 16GB public-repo runner with Chromium
# to spare; it does NOT fit the 7GB private-repo runner. Both smoke suites
# passed on exactly this slice, at exactly this heap, with the other 26
# services stopped — so the list is sufficient, not merely plausible.
# Adding a service here costs more than its own memory: check what it drags in.
SMOKE_SERVICES="postgres kafka redis keycloak gateway
  product-catalog product-ordering product-inventory party-account
  shopping-cart payment payment-method promotion qualification policy
  document user-roles storefront"

case "$TIER" in
  smoke) SERVICES="$SMOKE_SERVICES" ;;
  full)  SERVICES="" ;;  # empty = every service in the default profile
  *)     echo "usage: ops/ci-fleet.sh [smoke|full]" >&2; exit 64 ;;
esac

# Cap every JVM. The images read $JAVA_OPTS (see any service Dockerfile), so an
# override file generated here beats editing 95 compose blocks by hand.
OVERRIDE=".ci-fleet.override.yml"
{
  echo "# generated by ops/ci-fleet.sh — do not commit"
  echo "services:"
  for svc in $(docker compose config --services 2>/dev/null); do
    case "$svc" in postgres|kafka|redis|keycloak|minio|azurite) continue ;; esac
    # Cap EVERY service, not just the named slice: compose honours depends_on,
    # so asking for 18 services actually starts 33 (measured). The extras are
    # real JVMs on the same runner, and an override entry for a service that
    # never starts costs nothing.
    # Same shape the compose file already uses for the laptop ("21 JVMs share
    # one VM"), tightened: metaspace stays bounded, and a runner gains more
    # from a serial collector and skipping C2 than it loses in throughput.
    printf '  %s:\n    environment:\n      JAVA_OPTS: "-Xmx%s -XX:MaxMetaspaceSize=128m -XX:+UseSerialGC -XX:TieredStopAtLevel=1"\n' \
      "$svc" "$HEAP"
  done
} > "$OVERRIDE"
echo "[ci-fleet] $TIER: capped $(grep -c 'JAVA_OPTS' "$OVERRIDE") JVMs at $HEAP"

DC="docker compose -f docker-compose.yml -f $OVERRIDE"

echo "[ci-fleet] infrastructure first — a service that starts before its database dies noisily"
$DC up -d postgres kafka redis keycloak || { echo "[ci-fleet] infrastructure failed to start" >&2; exit 1; }

# Keycloak imports realms on first boot; nothing that validates a token works
# until it answers. Wait for it specifically, before the rest.
deadline=$((SECONDS + READY_TIMEOUT))
until curl -fsS -m 5 -o /dev/null \
      http://127.0.0.1:8085/realms/bss/.well-known/openid-configuration 2>/dev/null; do
  [ $SECONDS -lt $deadline ] || { echo "[ci-fleet] keycloak never answered" >&2
                                  docker logs --tail 60 bss-keycloak >&2 || true; exit 1; }
  sleep 5
done
echo "[ci-fleet] keycloak ready"

# shellcheck disable=SC2086
$DC up -d $SERVICES || { echo "[ci-fleet] compose up failed" >&2; exit 1; }

echo "[ci-fleet] waiting for the front door (gateway + catalog through it)"
deadline=$((SECONDS + READY_TIMEOUT))
until [ "$(curl -s -m 5 -o /dev/null -w '%{http_code}' \
      'http://127.0.0.1:8080/tmf-api/productCatalogManagement/v4/productOffering?limit=1')" = "200" ]; do
  if [ $SECONDS -ge $deadline ]; then
    echo "[ci-fleet] the gateway never served the catalog — unhealthy containers:" >&2
    docker ps -a --format '{{.Names}}\t{{.Status}}' | grep -vi ' Up .*healthy' >&2 || true
    for c in $(docker ps -a --format '{{.Names}}' | grep '^bss-'); do
      case "$(docker inspect -f '{{.State.Health.Status}}' "$c" 2>/dev/null)" in
        healthy) ;;
        *) echo "::group::$c"; docker logs --tail 40 "$c" 2>&1 | tail -40; echo "::endgroup::" ;;
      esac
    done
    exit 1
  fi
  sleep 10
done

echo "[ci-fleet] $TIER fleet ready: $(docker ps --format '{{.Names}}' | grep -c '^bss-') containers up"
exit 0
